In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = '../data/kkbox/'

In [3]:
f_app = os.path.join(dir_data, 'train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ../data/kkbox/train.csv


In [4]:
app_train.head(10)

msno  \
0  FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=   
1  Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=   
2  Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=   
3  Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=   
4  FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=   

                                        song_id source_system_tab  \
0  BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=           explore   
1  bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=        my library   
2  JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=        my library   
3  2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=        my library   
4  3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=           explore   

    source_screen_name      source_type  target  
0              Explore  online-playlist       1  
1  Local playlist more   local-playlist       1  
2  Local playlist more   local-playlist       1  
3  Local playlist more   local-playlist       1  
4              Explore  online-playlist       1

In [10]:
app_train['source_system_tab'].unique()

array(['explore', 'my library', 'search', 'discover', nan, 'radio',
       'listen with', 'notification', 'settings'], dtype=object)

In [11]:
app_train['source_screen_name'].unique()

array(['Explore', 'Local playlist more', nan, 'My library',
       'Online playlist more', 'Album more', 'Discover Feature',
       'Unknown', 'Discover Chart', 'Radio', 'Artist more', 'Search',
       'Others profile more', 'Search Trends', 'Discover Genre',
       'My library_Search', 'Search Home', 'Discover New',
       'Self profile more', 'Concert', 'Payment'], dtype=object)

In [12]:
app_train['source_type'].unique()

array(['online-playlist', 'local-playlist', 'local-library',
       'top-hits-for-artist', 'album', nan, 'song-based-playlist',
       'radio', 'song', 'listen-with', 'artist', 'topic-article-playlist',
       'my-daily-playlist'], dtype=object)

In [15]:
for feature in app_train.columns.tolist():
    print(feature, app_train[feature].unique())

msno ['FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg='
 'Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8='
 'uHqAtShXTRXju5GE8ri3ITsVFepPf8jUoCF7ffNOuqE=' ...
 '4N9yZKANKrn3HQIBhoVhcTEhyyRceozpTcnnqsQ+gss='
 'pSXUjXoK/eKqB0much1HvcBsOUTxPiCaC8WYUT/9fxg='
 'oHMpaCQRI6fzq/jamfTvv5tFfukkE9/VERi7/CfQ9M0=']
song_id ['BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik='
 'bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM='
 'JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=' ...
 'SZZUaT+kWlIDkjgJqK5VJls94gArFT1BgkrFLjvJVIc='
 '7+DNPp8HiFDXlQmNejGezfdJ15eXGms1PmRCwtc+zVQ='
 'WJzitiYM7ddyalCdx8/Gkkt1UFSp2t/0ZY74CrMGvWg=']
source_system_tab ['explore' 'my library' 'search' 'discover' nan 'radio' 'listen with'
 'notification' 'settings']
source_screen_name ['Explore' 'Local playlist more' nan 'My library' 'Online playlist more'
 'Album more' 'Discover Feature' 'Unknown' 'Discover Chart' 'Radio'
 'Artist more' 'Search' 'Others profile more' 'Search Trends'
 'Discover Genre' 'My library_Search' 'Search Home' 'Discover N

In [5]:
f_app = os.path.join(dir_data, 'songs.csv')
print('Path of read in data: %s' % (f_app))
app_songs = pd.read_csv(f_app)

Path of read in data: ../data/kkbox/songs.csv


In [6]:
app_songs.head(10)

song_id  song_length genre_ids  \
0  CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=       247640       465   
1  o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=       197328       444   
2  DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=       231781       465   
3  dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=       273554       465   
4  W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=       140329       726   

        artist_name                            composer     lyricist  language  
0  張信哲 (Jeff Chang)                                  董貞          何啟弘       3.0  
1         BLACKPINK  TEDDY|  FUTURE BOUNCE|  Bekuh BOOM        TEDDY      31.0  
2      SUPER JUNIOR                                 NaN          NaN      31.0  
3             S.H.E                                 湯小康          徐世珍       3.0  
4              貴族精選                         Traditional  Traditional      52.0

In [16]:
for feature in app_songs.columns.tolist():
    print(feature, app_songs[feature].unique())

song_id ['CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E='
 'o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU='
 'DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=' ...
 '9KxSvIjbJyJzfEVWnkMbgR6dyn6d54ot0N5FKyKqii8='
 'UO8Y2MR2sjOn2q/Tp8/lzZTGKmLEvwZ20oWanG4XnYc='
 'V/9qPSUOGT0FeIGBhDIZRRz5Y5yyjdXC2Z/+bJExo5s=']
song_length [247640 197328 231781 ...  34046 576130 417100]
genre_ids ['465' '444' '726' ... '786|958|2022' '1259|2107' '1138|2022']
artist_name ['張信哲 (Jeff Chang)' 'BLACKPINK' 'SUPER JUNIOR' ... 'Charley Brownn'
 'Avaleya and The GlitterHawks' 'Renato pezzella| Renato Pezzella']
composer ['董貞' 'TEDDY|  FUTURE BOUNCE|  Bekuh BOOM' nan ... 'Mawwell J. Mckinney'
 'Adam Lyons| Nathan Lyons| Timothy Voeten| Patrick Huerto| Thomas Davies| James Haigh'
 'Rodney Clawson| Vicky McGehee| David Lee Murphy']
lyricist ['何啟弘' 'TEDDY' nan ... 'Otoniel Santos' 'Stepz|Branco'
 'Rodney Clawson| Vicky McGehee| David Lee Murphy']
language [ 3. 31. 52. 17. 10. -1. 24. 59. 45. 38. nan]


In [7]:
f_app = os.path.join(dir_data, 'members.csv')
print('Path of read in data: %s' % (f_app))
app_members = pd.read_csv(f_app)

Path of read in data: ../data/kkbox/members.csv


In [8]:
app_members.head(10)

msno  city  bd gender  \
0  XQxgAYj3klVKjR3oxPPXYYFp4soD4TuBghkhMTD4oTw=     1   0    NaN   
1  UizsfmJb9mV54qE9hCYyU07Va97c0lCRLEQX3ae+ztM=     1   0    NaN   
2  D8nEhsIOBSoE6VthTaqDX8U6lqjJ7dLdr72mOyLya2A=     1   0    NaN   
3  mCuD+tZ1hERA/o5GPqk38e041J8ZsBaLcu7nGoIIvhI=     1   0    NaN   
4  q4HRBfVSssAFS9iRfxWrohxuk9kCYMKjHOEagUMV6rQ=     1   0    NaN   

   registered_via  registration_init_time  expiration_date  
0               7                20110820         20170920  
1               7                20150628         20170622  
2               4                20160411         20170712  
3               9                20150906         20150907  
4               4                20170126         20170613

In [17]:
app_members['city'].unique()

array([ 1, 13, 12, 15,  5,  6,  4, 11, 18, 22, 14,  8, 20,  3, 17, 10, 16,
        9, 21,  7, 19], dtype=int64)

In [18]:
app_members['gender'].unique()

array([nan, 'female', 'male'], dtype=object)

In [19]:
app_members['registered_via'].unique()

array([ 7,  4,  9,  3, 13, 16], dtype=int64)